__title__ = 'apace'
__description__ = 'Another Particle Accelerator Code'
__url__ = 'https://github.com/andreasfelix/apace'
__version__ = '0.1'
__author__ = 'Felix Andreas'
__license__ = 'GNU General Public License v3.0'
__copyright__ = 'Copyright 2019 Felix Andreas'
