__title__ = "apace"
__description__ = "Another Particle Accelerator Code"
__url__ = "https://github.com/andreasfelix/apace"
__version__ = "0.1.0"
__author__ = "Felix Andreas"
__license__ = "GNU General Public License v3.0"
